import argparse
import os
import sys

from transformers import AutoConfig

# Add project root to path
sys.path.append(os.getcwd())
try:
    from echo_hf.modeling_echo import EchoConfig, EchoForCausalLM
except ImportError:
    print("Error: Could not import Echo modules. Please run from project root.")
    sys.exit(1)


def format_num(num):
    if num >= 1_000_000_000:
        return f"{num/1_000_000_000:.2f}B"
    elif num >= 1_000_000:
        return f"{num/1_000_000:.2f}M"
    else:
        return f"{num:,}"


def generate_report(model_path, markdown=True):
    # Register Config
    AutoConfig.register("echo", EchoConfig)

    print(f"Loading model metadata from {model_path}...")
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)

    # Load model on CPU to count params
    print("Loading weights (CPU)...")
    model = EchoForCausalLM.from_pretrained(model_path, device_map="cpu", trust_remote_code=True)

    total_params = sum(p.numel() for p in model.parameters())

    # Component breakdown
    embedding_params = sum(p.numel() for p in model.model.embedding.parameters())
    blocks_params = sum(p.numel() for p in model.model.blocks.parameters())
    head_params = sum(p.numel() for p in model.lm_head.parameters())

    # Per block analysis (Block 0)
    b0 = model.model.blocks[0]
    sum(p.numel() for p in b0.gru_cell.parameters())
    sum(p.numel() for p in b0.mlp_up.parameters()) + sum(
        p.numel() for p in b0.mlp_down.parameters()
    )

    # DSRN Specifics
    (
        sum(p.numel() for p in b0.linear_gate.parameters())
        + sum(p.numel() for p in b0.linear_memory.parameters())
        + sum(p.numel() for p in b0.linear_read.parameters())
    )

    sum(p.numel() for p in b0.linear_pred.parameters()) + sum(
        p.numel() for p in [b0.surprise_lambda] if p is not None
    )

    sum(p.numel() for p in b0.norm_fast.parameters()) + sum(
        p.numel() for p in b0.norm_ff.parameters()
    )

    model_id = os.path.basename(os.path.abspath(model_path))

    if markdown:
        report = []
        report.append(f"# Model Card Analysis: {model_id}\n")

        report.append("## 🏗️ Architecture Details")
        report.append("| Property | Value |")
        report.append("| :--- | :--- |")
        report.append(f"| Model Type | {getattr(config, 'model_type', 'echo')} |")
        report.append(f"| Layers | {config.num_layers} |")
        report.append(f"| Hidden Dim | {config.hidden_size} |")
        report.append(f"| Attention Heads | {config.num_heads} |")
        report.append(f"| Vocab Size | {config.vocab_size} |")
        report.append("")

        report.append("## 📊 Parameter Breakdown")
        report.append("| Component | Parameters | % of Total |")
        report.append("| :--- | :--- | :--- |")
        report.append(
            f"| **Total** | **{format_num(total_params)} ({total_params:,})** | **100%** |"
        )
        report.append(
            f"| Embeddings | {format_num(embedding_params)} | {embedding_params/total_params:.2%} |"
        )
        report.append(
            f"| DSRN Blocks (Aggregate) | {format_num(blocks_params)} | {blocks_params/total_params:.2%} |"
        )
        report.append(f"| LM Head | {format_num(head_params)} | {head_params/total_params:.2%} |")
        report.append("")

        report.append("---")
        report.append("*Generated by `scripts/inspect_dsrn_params.py`*")

        return "\n".join(report)
    else:
        return f"Model: {model_id}\nTotal: {total_params:,}"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate model parameter report for model card.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to model directory")
    parser.add_argument("--output", type=str, default=None, help="Save report to file")

    args = parser.parse_args()

    report = generate_report(args.model_path)
    print(report)

    if args.output:
        with open(args.output, "w") as f:
            f.write(report)
        print(f"\nReport saved to {args.output}")
