import argparse
import os
import sys

from transformers import AutoConfig

# Add project root to path
sys.path.append(os.getcwd())
try:
    from echo_hybrid.modeling_hybrid import HybridEchoConfig, HybridEchoForCausalLM
except ImportError:
    print("Error: Could not import HybridEcho modules. Please run from project root.")
    sys.exit(1)


def format_num(num):
    if num >= 1_000_000_000:
        return f"{num/1_000_000_000:.2f}B"
    elif num >= 1_000_000:
        return f"{num/1_000_000:.2f}M"
    else:
        return f"{num:,}"


def generate_report(model_path, markdown=True):
    # Register Config
    AutoConfig.register("echo_hybrid", HybridEchoConfig)

    print(f"Analyzing Hybrid model: {model_path}...")
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)

    # Load model on CPU to count params
    print("Loading weights (CPU)...")
    model = HybridEchoForCausalLM.from_pretrained(
        model_path, device_map="cpu", trust_remote_code=True
    )

    total_params = sum(p.numel() for p in model.parameters())

    # 1. Embeddings
    embedding_params = sum(p.numel() for p in model.model.backbone.embed_tokens.parameters())

    # 2. Backbone (Attention + MLP)
    backbone_params = sum(p.numel() for p in model.model.backbone.layers.parameters())

    # 3. DSRN Injectors (Aggregate)
    injector_params = sum(p.numel() for p in model.model.memory_injectors.parameters())

    # 4. LM Head
    head_params = sum(p.numel() for p in model.lm_head.parameters())

    # --- Per Injector Analysis ---
    inj0 = model.model.memory_injectors[0]

    # DSRN Gates (Read/Update/Gate)
    gate_params = (
        sum(p.numel() for p in inj0.linear_gate.parameters())
        + sum(p.numel() for p in inj0.linear_memory.parameters())
        + sum(p.numel() for p in inj0.linear_read.parameters())
    )

    # Surprise Mechanism
    surprise_params = (
        sum(p.numel() for p in inj0.linear_pred.parameters()) + inj0.surprise_lambda.numel()
    )

    model_id = os.path.basename(os.path.abspath(model_path))

    if markdown:
        report = []
        report.append(f"# Model Card Analysis: {model_id}\n")

        report.append("## 🏗️ Hybrid Architecture Details")
        report.append("| Property | Value |")
        report.append("| :--- | :--- |")
        report.append("| Base Model | Qwen2 |")
        report.append(f"| Total Parameters | {format_num(total_params)} |")
        report.append(f"| Hidden Dim | {config.hidden_size} |")
        report.append(f"| Attention Layers | {config.num_hidden_layers} |")
        report.append(f"| DSRN Injectors | {len(model.model.memory_injectors)} |")
        report.append(f"| Injection Stride | {config.dsrn_injection_stride} |")
        report.append("")

        report.append("## 📊 Parameter Breakdown")
        report.append("| Component | Parameters | % of Total |")
        report.append("| :--- | :--- | :--- |")
        report.append(f"| **Total** | **{format_num(total_params)}** | **100%** |")
        report.append(
            f"| Embeddings | {format_num(embedding_params)} | {embedding_params/total_params:.2%} |"
        )
        report.append(
            f"| Backbone (Attention/MLP) | {format_num(backbone_params)} | {backbone_params/total_params:.2%} |"
        )
        report.append(
            f"| **DSRN Injectors** | **{format_num(injector_params)}** | **{injector_params/total_params:.2%}** |"
        )
        report.append(f"| LM Head | {format_num(head_params)} | {head_params/total_params:.2%} |")
        report.append("")

        report.append("## 🧩 DSRN Component (Per Injector)")
        report.append("| Sub-Component | Parameters | Description |")
        report.append("| :--- | :--- | :--- |")
        report.append(f"| Memory Gates | {format_num(gate_params)} | Recurrent state updates |")
        report.append(
            f"| Surprise Mechanism | {format_num(surprise_params)} | Dynamic focus/gating |"
        )
        report.append("")

        report.append("## 🚀 Efficiency Metric")
        dsrn_overhead = injector_params / (total_params - injector_params)
        report.append(
            f"- **DSRN Parameter Overhead**: {dsrn_overhead:.2%} additional parameters compared to base."
        )
        report.append(
            f"- **Hybrid Ratio**: 1 DSRN block for every {config.dsrn_injection_stride} attention layers."
        )
        report.append("")

        report.append("---")
        report.append("*Generated by `scripts/inspect_hybrid_params.py`*")

        return "\n".join(report)
    else:
        return f"Model: {model_id}\nTotal: {total_params:,}\nOverhead: {dsrn_overhead:.2%}"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate hybrid model parameter report.")
    parser.add_argument("--model_path", type=str, required=True, help="Path to model directory")
    parser.add_argument("--output", type=str, default=None, help="Save report to file")

    args = parser.parse_args()

    report = generate_report(args.model_path)
    print(report)

    if args.output:
        with open(args.output, "w") as f:
            f.write(report)
        print(f"\nReport saved to {args.output}")
